### ISSUE TITLE
pygame.sprite has no attribute 'truth'

### ISSUE THREAD

**Issue by randyheydon** [soapy1/CollisionTheorySim#1]
Full traceback:

```
Traceback (most recent call last):
  File "collision.py", line 156, in <module>
    check_collision() 
  File "collision.py", line 84, in check_collision
    b = pygame.sprite.truth(a)
AttributeError: 'module' object has no attribute 'truth'
```

No function named "truth" is mentioned in the [sprite module documentation](http://www.pygame.org/docs/ref/sprite.html).  I see that this line is trying to operate on the results of the previous line, a call to [groupcollide](http://www.pygame.org/docs/ref/sprite.html#pygame.sprite.groupcollide), which, according to the documentation, returns a dictionary of any colliding sprites.  If you simply want to know if any sprites collide, you just need to check if the returned dictionary is non-empty (ie: `a != {}`).

**Comment by randyheydon** [comment]
Since the problem has been fixed, this issue can be marked as closed.
